---
namespace: dummy-apps-space
base_url: lab.dev
apm:
  java_agent:
    image: docker.elastic.co/observability/apm-agent-java
    tag: 1.36.0


namespaces:
  - name: location1
    apps:
      - name: app1
        resources:
          requests:
            cpu: 100m
            memory: 125Mi
          limits:
            cpu: 150m
            memory: 150Mi
      - name: app2
        resources:
          requests:
            cpu: 100m
            memory: 125Mi
          limits:
            cpu: 150m
            memory: 150Mi
      - name: app3
        resources:
          requests:
            cpu: 100m
            memory: 125Mi
          limits:
            cpu: 150m
            memory: 150Mi
