---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: dummy-app
    service: dummy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
        service: dummy-app
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      ###################### Shared volume and init container ##########################
      volumes:
      - name: elastic-apm-agent
        emptyDir: {}
      initContainers:
      - name: elastic-java-agent
        image: {{ .Values.apm.java_agent.image }}:{{ .Values.apm.java_agent.tag }}
        volumeMounts:
        - mountPath: /elastic/apm/agent
          name: elastic-apm-agent
        command: ['cp', '-v', '/usr/agent/elastic-apm-agent.jar', '/elastic/apm/agent']
      ##################################################################################
      containers:
      - name: petclinic
        image: eyalkoren/pet-clinic:without-agent
      ######################### Volume path and agent config ###########################
      ################# keytool -import -noprompt -trustcacerts -alias apm-server-apm-http.monitoring-tools-poc.svc.cluster.local -file servicecertificate -keystore "$JAVA_HOME/lib/security/cacerts"
        volumeMounts:
        - mountPath: /elastic/apm/agent
          name: elastic-apm-agent
        env:
        - name: ELASTIC_APM_SERVER_URL
          value: "http://apm-server.svc.cluster.local:8200"
        - name: ELASTIC_APM_SERVICE_NAME
          value: dummy-app
        - name: ELASTIC_APM_APPLICATION_PACKAGES
          value: org.springframework.samples.petclinic
        - name: ELASTIC_APM_ENVIRONMENT
          value: dev
        - name: ELASTIC_APM_LOG_LEVEL
          value: DEBUG
        - name: ELASTIC_APM_SECRET_TOKEN
          value: "token"
        - name: JAVA_TOOL_OPTIONS
          value: '-javaagent:/elastic/apm/agent/elastic-apm-agent.jar'
        - name: ELASTIC_APM_GLOBAL_LABELS
          value: namespace=default
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
#        - name: ELASTIC_APM_VERIFY_SERVER_CERT
#          value: 'false'
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: dummy-app
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    service: dummy-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: dummy-app
spec:
  rules:
  - host: dummy-app-{{ .Release.Namespace }}.{{ .Values.base_url }}
    http:
      paths:
      - backend:
          service:
            name: dummy-app
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
